### ISSUE TITLE
how to add multiple sub topics

### ISSUE THREAD

**Issue by eklavyainfo** [debsahu/ESP-MQTT-AWS-IoT-Core#16]

**Comment by debsahu** [comment]
https://github.com/debsahu/ESP-MQTT-AWS-IoT-Core/blob/64817e28b0a7ca295af926a6c352a9b4d51ee15e/Arduino/MQTT/MQTT.ino#L127

**Comment by eklavyainfo** [comment]
> https://github.com/debsahu/ESP-MQTT-AWS-IoT-Core/blob/64817e28b0a7ca295af926a6c352a9b4d51ee15e/Arduino/MQTT/MQTT.ino#L127

thANKS
