### ISSUE TITLE
ESP8266 Reboooting after a while

### ISSUE THREAD

**Issue by yash2607** [debsahu/ESP-MQTT-AWS-IoT-Core#2]
First of All Thankyou for this code it has made connecting to Aws through Esp a lot easier.
Comming to the the issue
After few seconds of running the Esp8266 is constantly rebooting. It reboots after printing "Checking Wifiok". I am using the PubSub example without changing anything in the main code (just editing the secret file). I have update the library  (Arduino json & Esp8266 ) as told sharing the code (Esp8266.txt) & Serial monitor prints (Serial Prints.txt ) in a text file here
[Serial Prints.txt](https://github.com/debsahu/ESP-MQTT-AWS-IoT-Core/files/2787626/Serial.Prints.txt)

[Esp8266.txt](https://github.com/debsahu/ESP-MQTT-AWS-IoT-Core/files/2787611/Esp8266.txt)

**Comment by debsahu** [comment]
This code is not ready for consumption yet. I was not able to reconnect to AWS IoT on ESP8266 after a disconnect. So I wrote code to reboot after a MQTT disconnect, 
```
//Not sure why reconnecting to AWS via MQTT does not work correctly on ESP8266
//Something to do with BearSSL::WiFiClientSecure, go figure!
#ifdef ESP32
    checkWiFiThenMQTT(); //either methods should be ok
    //checkWiFiThenMQTTNonBlocking(); //either methods should be ok
#else
    checkWiFiThenReboot();
#endif
```

This has something to do with BeasrSSL::Wificlientsecure. I'm waiting to see what changes come to it via esp8266 Arduino to make it stable like ESP32. My code won't change for the future except the part highlighted.

**Comment by debsahu** [comment]
Now everything should be working just like ESP32.

**Comment by yash2607** [comment]
> Now everything should be working just like ESP32.

Thanks for this.! I will test the code and let you know.

**Comment by debsahu** [comment]
Closing as I was able to connect without rebooting multiple times. Reopen if you face this issue.
