### ISSUE TITLE
MQTT Connecting Failed

### ISSUE THREAD

**Issue by jareducherek** [debsahu/ESP-MQTT-AWS-IoT-Core#4]
Read through the other issue, still cannot find a fix. I have followed the steps a few times through now I cannot find the mistake I am making, any help is appreciated. 

I found a few errors but they didn't fix the problem: 

> updated THINGNAME
> updated time zone
> removed "http://" that I accidentally put in front of MQTT_HOST string. 

Here's my output:

13:58:34.988 -> Setting time using SNTPdone!
13:58:34.988 -> Current time: Tue Mar  5 03:58:35 2019
13:58:34.988 -> MQTT connecting SSL Error Code: 0
13:59:19.340 -> failed, reason -> Unknown Return Code < try again in 5 seconds

**Comment by debsahu** [comment]
https://github.com/debsahu/ESP-MQTT-AWS-IoT-Core/blob/00e8d67c8dc60ed3545fba1b37094b47999c96ec/Arduino/ChooseMQTTPubSub/ChooseMQTTPubSub.ino#L188

Could you add and post the serial output?
```
Serial.print("SSL Error Code: ");
Serial.println(net.getLastSSLError());
```

**Comment by jareducherek** [comment]
I followed the instructions again after completely deleting both the policy and thing. It is finally working! Thanks anyway for trying to help.

**Comment by debsahu** [comment]
sweet

**Comment by OkenKhuman** [comment]
> https://github.com/debsahu/ESP-MQTT-AWS-IoT-Core/blob/00e8d67c8dc60ed3545fba1b37094b47999c96ec/Arduino/ChooseMQTTPubSub/ChooseMQTTPubSub.ino#L188
> 
> Could you add and post the serial output?
> 
> ```
> Serial.print("SSL Error Code: ");
> Serial.println(net.getLastSSLError());
> ```

I got the same issue and after adding the debug code I got the below
```
SSL Error Code: 54
failed, reason -> Connect failed < try again 
```
I use esp8266

and regarding my AWS iot policy I use the below for testing
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "*"
    }
  ]
}
```

**Comment by OkenKhuman** [comment]
It works after altering the timezone

Thankyou for the code
