### ISSUE TITLE
MQTT.h: No such file or directory

### ISSUE THREAD

**Issue by adamaero** [debsahu/ESP-MQTT-AWS-IoT-Core#5]
```
C:\Users\Adam\Documents\Arduino\ESP-MQTT-AWS-IoT-Core-master\ESP-MQTT-AWS-IoT-Core-master\Arduino\MQTT\MQTT.ino:9:18: fatal error: MQTT.h: No such file or directory

 #include <MQTT.h>

                  ^

compilation terminated.

exit status 1
Error compiling for board NodeMCU 0.9 (ESP-12 Module).
```
I downloaded the libraries:
![library](https://user-images.githubusercontent.com/26505046/55269856-f198ac80-5265-11e9-9864-fa580621dcb6.PNG)

What am I missing[?](https://forum.arduino.cc/index.php?topic=606880)

**Comment by adamaero** [comment]
Where should `MQTT.h` be?
![image](https://user-images.githubusercontent.com/26505046/55277338-fd6b8980-52cc-11e9-8f24-8836060f9716.png)
![image](https://user-images.githubusercontent.com/26505046/55277340-0bb9a580-52cd-11e9-9edf-061355728b74.png)

**Comment by debsahu** [comment]
The library looks like it's installed correctly. Could you try compiling any of the examples from Arduino MQTT, does it compile?

**Comment by adamaero** [comment]
It was because arduino-mqtt-master, since it is a library, cannot be a subfolder of itself.
