### ISSUE TITLE
What needs to be edited? something in the supporting libraries?

### ISSUE THREAD

**Issue by adamaero** [debsahu/ESP-MQTT-AWS-IoT-Core#6]
I am trying to get the program to work with an esp8266 so I'm using this one:
C:\Users\Adam\Documents\Arduino\ESP-MQTT-AWS-IoT-Core-master\ESP-MQTT-AWS-IoT-Core-master\Arduino\MQTT

Are there things that need to be changed in the supporting libraries? All I've changed is the secrets.h[:](https://forum.arduino.cc/index.php?topic=607368)
![image](https://user-images.githubusercontent.com/26505046/55333784-94ffe200-545d-11e9-9eb3-78ff603c344f.png)

I don't understand why this is happening. I downloaded the JSON library:
C:\Users\Adam\Documents\Arduino\libraries\ArduinoJson-6.x

**Comment by debsahu** [comment]
It tells you to install a particular version of library that I've tested and confirmed that things work. I'm sure the newer versions would be fine, but at the time of writing this sketch ArduinoJson 6 was still in beta. I'll update the sketch to remove this restriction.

**Comment by adamaero** [comment]
`Arduino: 1.8.4 (Windows 7), Board: "NodeMCU 0.9 (ESP-12 Module), 80 MHz, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

MQTT:31: error: 'BearSSL' does not name a type

 BearSSL::X509List cert(cacert);

 ^

MQTT:32: error: 'BearSSL' does not name a type

 BearSSL::X509List client_crt(client_cert);

 ^

MQTT:33: error: 'BearSSL' does not name a type

 BearSSL::PrivateKey key(privkey);

 ^

C:\Users\Adam\Documents\Arduino\ESP-MQTT-AWS-IoT-Core-master\ESP-MQTT-AWS-IoT-Core-master\Arduino\MQTT\MQTT.ino: In function 'void connectToMqtt(bool)':

MQTT:120: error: 'THINGNAME' was not declared in this scope

     if (client.connect(THINGNAME))

                        ^

C:\Users\Adam\Documents\Arduino\ESP-MQTT-AWS-IoT-Core-master\ESP-MQTT-AWS-IoT-Core-master\Arduino\MQTT\MQTT.ino: In function 'void sendData()':

MQTT:185: error: no matching function for call to 'ArduinoJson6100_000::BasicJsonDocument<ArduinoJson6100_000::DefaultAllocator>::BasicJsonDocument()'

   DynamicJsonDocument jsonBuffer;

                       ^

C:\Users\Adam\Documents\Arduino\ESP-MQTT-AWS-IoT-Core-master\ESP-MQTT-AWS-IoT-Core-master\Arduino\MQTT\MQTT.ino:185:23: note: candidates are:

In file included from C:\Users\Adam\Documents\Arduino\libraries\ArduinoJson-6.x\src/ArduinoJson/Document/DynamicJsonDocument.hpp:7:0,

                 from C:\Users\Adam\Documents\Arduino\libraries\ArduinoJson-6.x\src/ArduinoJson.hpp:21,

                 from C:\Users\Adam\Documents\Arduino\libraries\ArduinoJson-6.x\src/ArduinoJson.h:9,

                 from C:\Users\Adam\Documents\Arduino\ESP-MQTT-AWS-IoT-Core-master\ESP-MQTT-AWS-IoT-Core-master\Arduino\MQTT\MQTT.ino:10:

C:\Users\Adam\Documents\Arduino\libraries\ArduinoJson-6.x\src/ArduinoJson/Document/BasicJsonDocument.hpp:50:3: note: ArduinoJson6100_000::BasicJsonDocument<TAllocator>::BasicJsonDocument(ArduinoJson6100_000::VariantRef) [with TAllocator = ArduinoJson6100_000::DefaultAllocator]

   BasicJsonDocument(VariantRef src)

   ^

C:\Users\Adam\Documents\Arduino\libraries\ArduinoJson-6.x\src/ArduinoJson/Document/BasicJsonDocument.hpp:50:3: note:   candidate expects 1 argument, 0 provided

C:\Users\Adam\Documents\Arduino\libraries\ArduinoJson-6.x\src/ArduinoJson/Document/BasicJsonDocument.hpp:43:3: note: template<class T> ArduinoJson6100_000::BasicJsonDocument<TAllocator>::BasicJsonDocument(const T&, typename ArduinoJson6100_000::enable_if<ArduinoJson6100_000::IsVisitable<T>::value>::type*)

   BasicJsonDocument(const T& src,

   ^

C:\Users\Adam\Documents\Arduino\libraries\ArduinoJson-6.x\src/ArduinoJson/Document/BasicJsonDocument.hpp:43:3: note:   template argument deduction/substitution failed:

C:\Users\Adam\Documents\Arduino\ESP-MQTT-AWS-IoT-Core-master\ESP-MQTT-AWS-IoT-Core-master\Arduino\MQTT\MQTT.ino:185:23: note:   candidate expects 2 arguments, 0 provided

   DynamicJsonDocument jsonBuffer;

                       ^

In file included from C:\Users\Adam\Documents\Arduino\libraries\ArduinoJson-6.x\src/ArduinoJson/Document/DynamicJsonDocument.hpp:7:0,

                 from C:\Users\Adam\Documents\Arduino\libraries\ArduinoJson-6.x\src/ArduinoJson.hpp:21,

                 from C:\Users\Adam\Documents\Arduino\libraries\ArduinoJson-6.x\src/ArduinoJson.h:9,

                 from C:\Users\Adam\Documents\Arduino\ESP-MQTT-AWS-IoT-Core-master\ESP-MQTT-AWS-IoT-Core-master\Arduino\MQTT\MQTT.ino:10:

C:\Users\Adam\Documents\Arduino\libraries\ArduinoJson-6.x\src/ArduinoJson/Document/BasicJsonDocument.hpp:36:3: note: ArduinoJson6100_000::BasicJsonDocument<TAllocator>::BasicJsonDocument(const ArduinoJson6100_000::BasicJsonDocument<TAllocator>&) [with TAllocator = ArduinoJson6100_000::DefaultAllocator]

   BasicJsonDocument(const BasicJsonDocument& src)

   ^

C:\Users\Adam\Documents\Arduino\libraries\ArduinoJson-6.x\src/ArduinoJson/Document/BasicJsonDocument.hpp:36:3: note:   candidate expects 1 argument, 0 provided

C:\Users\Adam\Documents\Arduino\libraries\ArduinoJson-6.x\src/ArduinoJson/Document/BasicJsonDocument.hpp:33:12: note: ArduinoJson6100_000::BasicJsonDocument<TAllocator>::BasicJsonDocument(size_t, TAllocator) [with TAllocator = ArduinoJson6100_000::DefaultAllocator; size_t = unsigned int]

   explicit BasicJsonDocument(size_t capa, TAllocator allocator = TAllocator())

            ^

C:\Users\Adam\Documents\Arduino\libraries\ArduinoJson-6.x\src/ArduinoJson/Document/BasicJsonDocument.hpp:33:12: note:   candidate expects 2 arguments, 0 provided

C:\Users\Adam\Documents\Arduino\ESP-MQTT-AWS-IoT-Core-master\ESP-MQTT-AWS-IoT-Core-master\Arduino\MQTT\MQTT.ino: In function 'void setup()':

MQTT:208: error: 'THINGNAME' was not declared in this scope

   WiFi.hostname(THINGNAME);

                 ^

MQTT:221: error: 'class WiFiClientSecure' has no member named 'setTrustAnchors'

   net.setTrustAnchors(&cert);

       ^

MQTT:221: error: 'cert' was not declared in this scope

   net.setTrustAnchors(&cert);

                        ^

MQTT:222: error: 'class WiFiClientSecure' has no member named 'setClientRSACert'

   net.setClientRSACert(&client_crt, &key);

       ^

MQTT:222: error: 'client_crt' was not declared in this scope

   net.setClientRSACert(&client_crt, &key);

                         ^

MQTT:222: error: 'key' was not declared in this scope

   net.setClientRSACert(&client_crt, &key);

                                      ^

exit status 1
'BearSSL' does not name a type
`
![image](https://user-images.githubusercontent.com/26505046/55341306-034ba100-546c-11e9-9be5-5bd138e2f95b.png)

Is there key information that should be added (left box), like the old version of this library required (on the right)?

**Comment by adamaero** [comment]
All I've changed is `secrets.h`. It seems there is a bunch of things in MQTT that need to be changed like various keys.

**Comment by debsahu** [comment]
Are you on latest arduino-esp8266 core? BearSSL was introduced as default in core 2.5.0 and above.

**Comment by debsahu** [comment]
I just pushed updates that removes the ArduinoJson requirements, now all that is required is ArduinoJson v6.7.x or higher. Everything should compile on latest core: https://travis-ci.com/debsahu/ESP-MQTT-AWS-IoT-Core. All you need to connect to AWS are the values in **secrets.h**.

**Comment by adamaero** [comment]
I have Arduino IDE version 1.8.4... I put the latest Arduino core in my library folder.

**Comment by debsahu** [comment]
No not the IDE, esp8266 arduino core >> https://github.com/esp8266/Arduino

**Comment by debsahu** [comment]
Tools > Board > Boards Manager> Search "esp8266" > version 2.5.0 > Install/Update
![image](https://user-images.githubusercontent.com/24575521/55345215-5d089700-547d-11e9-913b-5e4b9a4b251b.png)

**Comment by adamaero** [comment]
Thank you very much. I had 3.4.1
